[package]
name = "sims3_rs"
version = "0.2.0"
authors = ["Kitlith <kitlith@kitl.pw>"]
edition = '2018'

# some of these are only for the binaries...
[dependencies]
scroll = "0.9"
scroll_derive = "*"
memmap = "0.6.2"
num-traits = "0.2"
num-derive = "0.2"
sha2 = "0.7"
walkdir = "2"
generic-array = "0.11.1"
quick-error = "1.2.2"
byteorder = "1"
lazy-init = "0.3.0"
rayon = "1.0.2"
lazy_static = "1.1.0"
structopt = "0.2.10"

[dev-dependencies]
